services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_mqtt
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf

configs:
    mosquitto_config:
        file: ./mosquitto.conf

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:
