services:
  content:
    build:
      context: ../src/content
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/content_db
    networks:
      - my_network

  device:
    build:
      context: ../src/device
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    depends_on:
      - mosquitto
      - content
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - CONTENT_SERVICE_URL=http://content:8000
      - DEVICE_ID=1
      - DEVICE_API_KEY=${DEVICE_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - my_network

  weather:
    build:
      context: ../src/weather
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - my_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: content_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../src/frontend/web-ui:/var/www/html
    depends_on:
      - content
      - device
      - weather
    networks:
      - my_network

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:

networks:
  my_network:
    driver: bridge
