name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push Content Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/content
          load: true
          tags: |
            content-management-service:latest

      - name: Build and push Device Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/device
          load: true
          tags: |
            device-management-service:latest

      - name: Build and push Weather Service
        uses: docker/build-push-action@v4
        with:
          context: ./services/weather
          load: true
          tags: |
            weather-service:latest
