name: Build Docker Images

on:
  push:
    branches:
      - main  # Или ваша основная ветка, например master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Content Management Service image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/content_service
          push: false
          tags: content-management-service:latest

      - name: Build Device Management Service image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/device_service
          push: false
          tags: device-management-service:latest

      - name: Build Weather Service image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/weather_service
          push: false
          tags: weather-service:latest
